### ISSUE TITLE
wrong final block length error while decrypting

### ISSUE THREAD

**Issue by mridah** [invalidred/cryptlib#3]
I'm using this line of code to decrypt a string:

    var decryptedString = cryptoLib.decrypt(myString, returnShaKey, process.env.RETURN_TOKEN_AES_IV);

It works fine when I pass the generated encrypted string in `myString`

But suppose I sent no string / wrong string, it gives this error:

> Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
   at Decipheriv.final (crypto.js:181:26)
   at CryptLib._encryptDecrypt (/home/ubuntu/rotor/api/node_modules/cryptlib/dist/CryptLib.js:98:24)
   at CryptLib.decrypt (/home/ubuntu/rotor/api/node_modules/cryptlib/dist/CryptLib.js:180:19)
   at guard (/home/ubuntu/rotor/api/app.js:94:33)
   at Layer.handle [as handle_request] (/home/ubuntu/rotor/api/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/ubuntu/rotor/api/node_modules/express/lib/router/index.js:312:13)
   at /home/ubuntu/rotor/api/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/home/ubuntu/rotor/api/node_modules/express/lib/router/index.js:330:12)
   at next (/home/ubuntu/rotor/api/node_modules/express/lib/router/index.js:271:10)
   at jsonParser (/home/ubuntu/rotor/api/node_modules/body-parser/lib/types/json.js:109:7)
   at Layer.handle [as handle_request] (/home/ubuntu/rotor/api/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/home/ubuntu/rotor/api/node_modules/express/lib/router/index.js:312:13)
   at /home/ubuntu/rotor/api/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/home/ubuntu/rotor/api/node_modules/express/lib/router/index.js:330:12)
   at next (/home/ubuntu/rotor/api/node_modules/express/lib/router/index.js:271:10)
   at urlencodedParser (/home/ubuntu/rotor/api/node_modules/body-parser/lib/types/urlencoded.js:91:7)

It shows this error when I open the API url in my browser as well. Is there a way I can handle this error and display a custom message (so the API doesn't appear buggy) ?? @invalidred

**Comment by invalidred** [comment]
hi @mridah maybe you can surround the code in try/catch block and try.

**Comment by mridah** [comment]
hi @invalidred , sorry was a little busy...thanks :) 
it's working fine now !!
